services:
  webapplication1:
    image: webapplication-image
    container_name: webapplication-container 
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
  webapplication2:
    image: webapplication2-image
    container_name: webapplication2-container 
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile
  sqlserver.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver.db
    restart: always
    environment:
      SA_PASSWORD: Password12*
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - sqlserver-data-microservice1:/var/opt/mssql
  
