services:
  webapplicationfordocker:
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5000:8080"
    volumes:
      - webapplicationfordocker-data:/app/wwwroot/images
  webapplicationfordocker2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5002:8080"
volumes:
  webapplicationfordocker-data: